apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-api
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: devops-api=d4rkghost47/gitops-api
    argocd-image-updater.argoproj.io/devops-api.update-strategy: newest-build
    argocd-image-updater.argoproj.io/devops-api.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/devops-api.helm.image-tag: image.tag 
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/write-back-target: helmvalues:values.yaml
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:evil-cloud/kcd-rollout-config.git
    targetRevision: HEAD
    path: .
    helm:
      valueFiles:
        - values.yaml
      skipSchemaValidation: false
      skipCrds: false
  destination:
    server: https://kubernetes.default.svc
    namespace: devops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
      - ignoreMissingValueFiles=true

    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 5

